-- DDL Schema for Auto-Initialization

DROP TABLE IF EXISTS forum_comments CASCADE;
DROP TABLE IF EXISTS forum_posts CASCADE;
DROP TABLE IF EXISTS interviews CASCADE;
DROP TABLE IF EXISTS applications CASCADE;
DROP TABLE IF EXISTS companies CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS admins CASCADE;

-- Admins Table
CREATE TABLE admins (
    admin_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
);

-- Students Table
CREATE TABLE students (
    student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    cgpa NUMERIC(4, 2),
    branch VARCHAR(50),
    graduation_year INT,
    skills TEXT,
    extracted_skills TEXT,
    resume_url VARCHAR(512)
);

-- Companies Table
CREATE TABLE companies (
    company_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL,
    role VARCHAR(100) NOT NULL,
    package NUMERIC(10, 2),
    eligibility_criteria NUMERIC(4, 2),
    description TEXT,
    last_date DATE NOT NULL
);

-- Applications Table
CREATE TABLE applications (
    application_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
    company_id INT NOT NULL REFERENCES companies(company_id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL DEFAULT 'APPLIED',
    match_score INT DEFAULT 0,
    application_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_student_company UNIQUE (student_id, company_id)
);

-- Interviews Table
CREATE TABLE interviews (
    interview_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id INT NOT NULL REFERENCES applications(application_id) ON DELETE CASCADE,
    scheduled_time TIMESTAMP NOT NULL,
    duration_minutes INT DEFAULT 60,
    round_name VARCHAR(100) NOT NULL,
    location_or_link VARCHAR(512),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Forum Posts Table
CREATE TABLE forum_posts (
    post_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT REFERENCES students(student_id) ON DELETE SET NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT 'General',
    is_anonymous BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Forum Comments Table
CREATE TABLE forum_comments (
    comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INT NOT NULL REFERENCES forum_posts(post_id) ON DELETE CASCADE,
    student_id INT REFERENCES students(student_id) ON DELETE SET NULL,
    content TEXT NOT NULL,
    is_anonymous BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
